apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ums-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ums.umsdevopsdemo.in
      secretName: ums-tls
  rules:
    - host: ums.umsdevopsdemo.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ums-service
                port:
                  number: 80
